files:
  - source: /Patchers_Auto_Update/RiiConnect24Patcher/UPDATE/Translation_Files/
    translation: >-
      /Patchers_Auto_Update/RiiConnect24Patcher/UPDATE/Translation_Files/Language_%language%.bat
